version: "3.8"

services:
  server:
    image: prudenca08/cicd-be:latest
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - hms
    container_name: server
    hostname: server
    networks:
      - mynetwork

    ports:
      - 8080:8080

    deploy:
      restart_policy:
        condition: on-failure

  hms:
    container_name: hms
    hostname: db-hms.cvkywxwrdmsr.ap-southeast-1.rds.amazonaws.com
    networks:
      - mynetwork

volumes:
  hms-volume:

networks:
  mynetwork:
    driver: bridge
