version: "3.8"

services:
  server:
    image: prudenca08/cicd-be:latest
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8080:8080

    deploy:
      restart_policy:
        condition: on-failure
